# Site settings
title: Pythia Online
email: erick.peirson@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  From the trenches of computational humanities.
long_description: >
  Bite-size forrays into computational analysis and infrastructure development.
baseurl: "/pythia/" # the subpath of your site, e.g. /blog/
url: "http://erickpeirson.github.io" # the base hostname & protocol for your site
twitter_username: captbarberousse
github_username:  erickpeirson
academia_username: erickpeirson

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 5

kramdown:
  input: GFM

category_archive:
  slugify: true
  path: /category